### ISSUE TITLE
Node is showing "Honeybee is not installed,install it from package manager"

### ISSUE THREAD

**Issue by charan1644** [ladybug-analysis-tools/honeybee-grasshopper#111]
![bug2](https://user-images.githubusercontent.com/53040180/74324317-e16dbb00-4dac-11ea-848a-4bf9cc16079d.JPG)

![bug1](https://user-images.githubusercontent.com/53040180/74324303-dadf4380-4dac-11ea-84d2-2211bb89f14e.JPG)

Please let me know the issue at the earliest

**Comment by mostaphaRoudsari** [comment]
This is a path issue. Basically the nodes cannot find where Honeybee package is installed. I have opened an issue on Dynamo's repository. Once the issue is addressed we can modify the nodes to address this issue.

https://github.com/DynamoDS/Dynamo/issues/6894
