### ISSUE TITLE
error honeybee-dynamo with GBS generated EPW file

### ISSUE THREAD

**Issue by koubaaleila** [ladybug-analysis-tools/honeybee-grasshopper#82]
Hello! 
i was testing honeybee-dynamo with the epw files of tunisia 147014 but the skymatrix writes that it's not available. However when the componment of solar radiation was in ladybug 1.7 it worked!

**Comment by mostaphaRoudsari** [comment]
The only weather file that I can file is [this one](https://www.energyplus.net/weather-download/africa_wmo_region_1/TUN//TUN_Tunis.607150_IWEC/all). Can you zip and upload your weather file?

**Comment by koubaaleila** [comment]
Le lundi 19 février 2018 à 15:52:57 UTC+1, Mostapha Sadeghipour Roudsari <notifications@github.com> a écrit :  
 
 
The only weather file that I can file is this one. Can you zip and upload your weather file?

**Comment by koubaaleila** [comment]
[GBS_06M12_02_147014.zip](https://github.com/ladybug-tools/honeybee-dynamo/files/1737217/GBS_06M12_02_147014.zip)

**Comment by koubaaleila** [comment]
hi mustapha. I still look for an answer.. the station is not valid also for dynamo honeybee
![capture147](https://user-images.githubusercontent.com/24694950/38633585-15aea89a-3db8-11e8-89d8-066cf857da7b.png)

**Comment by mostaphaRoudsari** [comment]
Hi @koubaaleila, What is the error from run_radiance node?

**Comment by mostaphaRoudsari** [comment]
I checked the weather file and there are some strange inputs for <not available>. I replaced them with NA and now everything is running fine.

![image](https://user-images.githubusercontent.com/2915573/38650245-c7ec26d0-3dc8-11e8-97d5-4b32b12ec699.png)

Here is the modified file:  [GBS_06M12_02_147014_fixed.zip](https://github.com/ladybug-tools/honeybee-dynamo/files/1900937/GBS_06M12_02_147014_fixed.zip)

**Comment by koubaaleila** [comment]
thank you very much.

**Comment by koubaaleila** [comment]
what is the explication of different values from ladybug 1.7 and honeybee for the same hour?
for exemple i calculated for southern façade on 01/01 at 10 
i had 333,070581605999 with ladybug 1.7 and now 335

**Comment by mostaphaRoudsari** [comment]
In honeybee we round the numbers. and the original number was probably 333.070581605999 (. instead of ,). See this for an answer to your question: http://discourse.ladybug.tools/t/question-why-every-time-the-simulation-results-is-not-the-same/590

I'm closing this issue since the original issue is resolved.
