### ISSUE TITLE
Error-Run randiance analysis

### ISSUE THREAD

**Issue by Anthindi** [ladybug-analysis-tools/honeybee-grasshopper#84]
Hello everyone,
I'm facing an issue with ladybug package  specifically with the run radiance analysis node, not really sure what is the problem it keeps on giving me error after creating the file
I uploaded the workflow, 
hope this will work,
thank you

**Comment by mostaphaRoudsari** [comment]
Hi @Anthindi,

This is a good question for the forum: http://discourse.ladybug.tools/

See [here](http://discourse.ladybug.tools/t/welcome-to-ladybug-tools-forum/8) on how to get an invitation to create an account if you don't have one.

PS: You forgot to upload the file. Please upload it to the forum. It's always helpful to provide more details about the error messages.
