### ISSUE TITLE
solar radiation for honeybee dynamo

### ISSUE THREAD

**Issue by koubaaleila** [ladybug-analysis-tools/honeybee-grasshopper#85]
when calculating solar radiation (hourly value) in dynamo honeybee can't calculate for more than one hoy at a time and also for cumulative value it can't calculate for a time step more than 1
![22](https://user-images.githubusercontent.com/24694950/38633404-70e1c0d6-3db7-11e8-99b2-a425ac181baa.png)

**Comment by mostaphaRoudsari** [comment]
>when calculating solar radiation (hourly value) in dynamo honeybee can't calculate for more than one hoy at a time

Not sure what you mean by this? Are you looking for cumulative results? You should use the node for cumulative values

> and also for cumulative value it can't calculate for a time step more than 1
This is true. For now we don't support sub-hourly simulation. See here: https://github.com/ladybug-tools/honeybee-dynamo/issues/37

**Comment by koubaaleila** [comment]
i need to calcular direct solar radiation for many hours.. when the componment was in ladybug 1.7 i made a noeud to do it. It allowed me to calculate radiation for many hours. But now, using honeybee i can't do it.
Thank you

**Comment by mostaphaRoudsari** [comment]
Use the `Sensor` node to create a sensor and then use `Sensor Hourly Values` get the results for several hours.

**Comment by koubaaleila** [comment]
very good thank you
