### ISSUE TITLE
comparing solar radiation values between dynamo ladybug 1.7 and honeybee

### ISSUE THREAD

**Issue by koubaaleila** [ladybug-analysis-tools/honeybee-grasshopper#87]
calculating solar radiation values on dynamo with ladybug 1.7 and honeybee 2.0 i need explication for different outcomes values for the same hour
![image](https://user-images.githubusercontent.com/24694950/38689163-c29f4356-3e72-11e8-912b-3eab71f2691c.png)

**Comment by mostaphaRoudsari** [comment]
@koubaaleila,

As I replied [here](https://twitter.com/PHDcomics/status/984451993103142913) radiance uses stochastic methods to calculate the values and small difference between the values is expected. You can find similar discussions on the forum which is the right place to ask questions like this: http://discourse.ladybug.tools/t/question-why-every-time-the-simulation-results-is-not-the-same/590

The difference between the values in your example is less than %2.
