### ISSUE TITLE
dynamo-ladybug installation not found

### ISSUE THREAD

**Issue by irfanirw** [ladybug-analysis-tools/honeybee-grasshopper#89]
Hello, 

I am using dynamo 2.00 with the recent ladybug and revit 2018.
I have a problem loading the epw file using dynamo ladybug.
The error message was like this:

> Traceback (most recent call last)
	FIle "<string", line 57, in <module>
ImportError: Ladybug is not installed! Install it from package manager

I have tried to check the problem here
[https://github.com/ladybug-tools/honeybee-dynamo/issues/88](url)
but I think i have no such problem with the file directory issue.
Anyway, my root directory: C:\Users\Irfan\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\Ladybug.

I also tried to run the script you gave in this issue
[https://github.com/ladybug-tools/honeybee-dynamo/issues/42#issuecomment-285682094](url)
but the result is different (picture below)
![image](https://user-images.githubusercontent.com/34654406/39351119-b06238a6-4a2a-11e8-8d52-65de519def3e.png)
I see that the package folder is blank.

Could you please help me with this issue?
Thanks

**Comment by mostaphaRoudsari** [comment]
Hi @irfanirw, and where is honeybee package installed on your machine?

**Comment by irfanirw** [comment]
Hello @mostaphaRoudsari , thank you very much for your response.

The directory of my package files is here:
> C:\Users\Irfan\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages

Is it any potential issue with my package directory?

**Comment by mostaphaRoudsari** [comment]
Hi @irfanirw, thank you for the quick reply. The difference is 2.0 versus 2 in filepath. I haven't tested the packages against Dynamo 2. The fix shouldn't be hard but it will take me some time before I can check the packages. Meanwhile can you use Dynamo 1.* for your work?

**Comment by irfanirw** [comment]
Hi, thank you for the response @mostaphaRoudsari 
I see.. While waiting for it, think I could use the previous version.
Hope you could solve it anyway.

Many thanks.

**Comment by mostaphaRoudsari** [comment]
Thanks. Will do. It's just a matter of time as I have several deadlines for this week and will be away for teaching workshops for another week. I have marked this as critical to get to it as soon as I can.

**Comment by JoshuaC-STN** [comment]
What do you mean by use Dynamo 1? I have this same error.

**Comment by ifolg** [comment]
I am here for the very same problem (the same error). My ladybug package works properly in Dynamo ver 1.3 but does not in ver. 2.0. The whole code and model is written in Dynamo 2.0 and for me it is critical to use Ladybug in new version of Dynamo. If I only knew that 2.0 brings me so much problem I would not choose that one, but I am working on my master thesis and it's new path of knowledge for me. 
My thought is that maybe these Notifications could be a cause, but inside them there is no clear message what should I do to remove them. 
Did you solve that issue? If yes, please help. 
![ladybug](https://user-images.githubusercontent.com/42203981/43828838-e4b3bad4-9afd-11e8-8c00-d8b42891387c.JPG)

**Comment by mostaphaRoudsari** [comment]
I just pushed new versions of ladybug and honeybee to package manager. Try to update your installation and try it in Dynamo 2.0
