### ISSUE TITLE
'Circle' object has no attribute 'Center'

### ISSUE THREAD

**Issue by ifolg** [ladybug-analysis-tools/honeybee-grasshopper#92]
I want to use node 'Generate Test Points by Grid Size', but mine surface is circle what seems to be a problem.  I tried to make rooms and then use 'Room to HBZ', but unfortunately Revit can not see floor under the dome as a room, because I have panels as my walls what complicates that issue. 

Dynamo creates surface by patch on the base of my dome, but then doesn't want to see it as a proper surface to generate test points. I tried to list it into the upper level @L3 but it didn't help, what I also attach to the screens.
A. is bug as @L2 list
B. is bug as @L3 list
C. is how I did the circle - data is taken from Revit arcs.

![a](https://user-images.githubusercontent.com/42203981/43951920-bc9cab3a-9c94-11e8-8bb0-218643fc87f8.JPG)
![b](https://user-images.githubusercontent.com/42203981/43951921-bcb936f6-9c94-11e8-9326-c251f1dbe1e6.JPG)
![c](https://user-images.githubusercontent.com/42203981/43951922-bcd579a6-9c94-11e8-9b20-cb480cef1156.JPG)

**Comment by mostaphaRoudsari** [comment]
Hi @ifolg, In such case it's easier if you use evaluate surface node from Dynamo. Also it seems you are using an older version of the plugins. Please update to the latest version.
