### ISSUE TITLE
Radiance Analysis

### ISSUE THREAD

**Issue by ghost** [ladybug-analysis-tools/honeybee-grasshopper#96]

**Comment by Thajnu** [comment]
Hi 

I am fairly new to Dynamo and have been working on a small project for Honeybee daylight analysis.

I managed to import geometry from REVIT and create analysis grid. But I am stuck at Run Radiance Analysis Node. This is very similar to #69 ,but could not find any solution for it.

EmptyFileError: Failed to load the results from an empty file: c:\ladybug\Test1gridbased_daylightcoeff\result/scene..default.ill
Double check inputs and outputs and make sure everything is run correctly.

![error](https://user-images.githubusercontent.com/19870353/46922451-4373b000-d001-11e8-979a-2229a281902b.JPG)
![folder](https://user-images.githubusercontent.com/19870353/46922452-4a9abe00-d001-11e8-9562-48d8368f7a83.JPG)

Appreciate any help!

[TEST.zip](https://github.com/ladybug-tools/honeybee-dynamo/files/2476894/TEST.zip)
